### ISSUE TITLE
boost/geometry.hpp: No such file or directory

### ISSUE THREAD

**Issue by vadik6666** [zhixinwang/frustum-convnet#6]
Hi! I am trying to compile this code, but at `bash make.sh` I got 
`box_ops.h:7:30: fatal error: boost/geometry.hpp: No such file or directory`

I tried to download **Boost** library from [here](https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2), unpack it and to add **Boost** folder location to a PATH variable. But I still get the same error.

@zhixinwang How can I fix it? I am working in Ubuntu 16.04.6 LTS, Python 3.7.4

**Comment by vadik6666** [comment]
solved with `sudo apt-get install libboost-dev`
